// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpkSnbp.Infrastructure.Database;

#nullable disable

namespace SpkSnbp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227105440_TambahRelasiSiswaHasil")]
    partial class TambahRelasiSiswaHasil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpkSnbp.Domain.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "Admin",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "Wali Kelas",
                            UserName = "Wali Kelas"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "Kepala Sekolah",
                            UserName = "Kepala Sekolah"
                        });
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.HasilPerhitungan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<double[]>("JarakSolusiIdealNegatif")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.PrimitiveCollection<double[]>("JarakSolusiIdealPositif")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<int>("Jurusan")
                        .HasColumnType("integer");

                    b.Property<double[,]>("MatriksPerhitungan")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double[,]>("MatriksTernormalisasi")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double[,]>("MatriksTernormalisasiTerbobot")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.PrimitiveCollection<double[]>("MaxKriteria")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.PrimitiveCollection<double[]>("MinKriteria")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.PrimitiveCollection<double[]>("SolusiIdealNegatif")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.PrimitiveCollection<double[]>("SolusiIdealPositif")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalPerhitungan")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TahunAjaranId");

                    b.ToTable("HasilPerhitungan");
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.Kriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bobot")
                        .HasColumnType("integer");

                    b.Property<int>("Jenis")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kriteria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bobot = 5,
                            Jenis = 0,
                            Nama = "Mata Pelajaran Kejuruan"
                        },
                        new
                        {
                            Id = 2,
                            Bobot = 4,
                            Jenis = 0,
                            Nama = "Mata Pelajaran Umum"
                        },
                        new
                        {
                            Id = 3,
                            Bobot = 4,
                            Jenis = 0,
                            Nama = "Sertifikat LSP"
                        },
                        new
                        {
                            Id = 4,
                            Bobot = 3,
                            Jenis = 0,
                            Nama = "Sertifikat TKA"
                        },
                        new
                        {
                            Id = 5,
                            Bobot = 2,
                            Jenis = 0,
                            Nama = "Ekstrakurikuler"
                        },
                        new
                        {
                            Id = 6,
                            Bobot = 1,
                            Jenis = 1,
                            Nama = "Absensi"
                        });
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.Siswa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Eligible")
                        .HasColumnType("integer");

                    b.Property<int?>("HasilPerhitunganId")
                        .HasColumnType("integer");

                    b.Property<int>("Jurusan")
                        .HasColumnType("integer");

                    b.Property<string>("NISN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("NilaiTopsis")
                        .HasColumnType("double precision");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HasilPerhitunganId");

                    b.HasIndex("TahunAjaranId");

                    b.ToTable("Siswa");
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.SiswaKriteria", b =>
                {
                    b.Property<int>("IdSiswa")
                        .HasColumnType("integer");

                    b.Property<int>("IdKriteria")
                        .HasColumnType("integer");

                    b.Property<double>("Nilai")
                        .HasColumnType("double precision");

                    b.HasKey("IdSiswa", "IdKriteria");

                    b.HasIndex("IdKriteria");

                    b.ToTable("SiswaKriteria");
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.TahunAjaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TahunAjaran");

                    b.HasData(
                        new
                        {
                            Id = 2025
                        });
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.HasilPerhitungan", b =>
                {
                    b.HasOne("SpkSnbp.Domain.ModulUtama.TahunAjaran", "TahunAjaran")
                        .WithMany("DaftarHasil")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.Siswa", b =>
                {
                    b.HasOne("SpkSnbp.Domain.ModulUtama.HasilPerhitungan", "HasilPerhitungan")
                        .WithMany("DaftarSiswa")
                        .HasForeignKey("HasilPerhitunganId");

                    b.HasOne("SpkSnbp.Domain.ModulUtama.TahunAjaran", "TahunAjaran")
                        .WithMany("DaftarSiswa")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HasilPerhitungan");

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.SiswaKriteria", b =>
                {
                    b.HasOne("SpkSnbp.Domain.ModulUtama.Kriteria", "Kriteria")
                        .WithMany("DaftarSiswaKriteria")
                        .HasForeignKey("IdKriteria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpkSnbp.Domain.ModulUtama.Siswa", "Siswa")
                        .WithMany("DaftarSiswaKriteria")
                        .HasForeignKey("IdSiswa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kriteria");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.HasilPerhitungan", b =>
                {
                    b.Navigation("DaftarSiswa");
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.Kriteria", b =>
                {
                    b.Navigation("DaftarSiswaKriteria");
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.Siswa", b =>
                {
                    b.Navigation("DaftarSiswaKriteria");
                });

            modelBuilder.Entity("SpkSnbp.Domain.ModulUtama.TahunAjaran", b =>
                {
                    b.Navigation("DaftarHasil");

                    b.Navigation("DaftarSiswa");
                });
#pragma warning restore 612, 618
        }
    }
}
